CI CI CI.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,17 +13,13 @@ test_coverage:
     - apt-get update -qq && apt-get install -y -qq lcov
     - dart test --coverage=coverage/
     - dart run coverage:format_coverage --lcov --in=coverage/ --out=coverage/lcov.info --package=. --report-on=lib
-    - genhtml coverage/lcov.info -o coverage/
-    # Checking coverage threshold
+    # Checking coverage threshold without generating detailed report
     - |
       LCOV_SUMMARY=$(lcov --summary coverage/lcov.info 2>&1)
-      COVERAGE_PERCENTAGE=$(echo $LCOV_SUMMARY | sed -n 's/.*lines......: \([0-9.]*%\).*/\1/p' | sed 's/%//')
+      COVERAGE_PERCENTAGE=$(echo $LCOV_SUMMARY | sed -n 's/.*lines......: \([0-9.]*%\).*/\1/p' | cut -d'.' -f1)
       echo "Coverage: $COVERAGE_PERCENTAGE%"
-      if [ $(echo "$COVERAGE_PERCENTAGE < 90" | bc -l) -eq 1 ]; then echo "Error: Coverage is below 90%" && exit 1; fi
+      if [ "$COVERAGE_PERCENTAGE" -lt 90 ]; then echo "Error: Coverage is below 90%" && exit 1; fi
   
-  artifacts:
-    paths:
-      - coverage
   tags:
     - docker
 
