OLOLOL

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,10 +15,11 @@ test_coverage:
     - dart run coverage:format_coverage --lcov --in=coverage/ --out=coverage/lcov.info --package=. --report-on=lib
     - genhtml coverage/lcov.info -o coverage/
     # Checking coverage threshold
-    - LCOV_SUMMARY=$(lcov --summary coverage/lcov.info 2>&1)
-    - COVERAGE_PERCENTAGE=$(echo $LCOV_SUMMARY | sed -n 's/.*lines......: \([0-9.]*%\).*/\1/p' | sed 's/%//')
-    - echo "Coverage: $COVERAGE_PERCENTAGE%"
-    - if [ $(echo "$COVERAGE_PERCENTAGE < 90" | bc -l) -eq 1 ]; then echo "Error: Coverage is below 90%" && exit 1; fi
+    - |
+      LCOV_SUMMARY=$(lcov --summary coverage/lcov.info 2>&1)
+      COVERAGE_PERCENTAGE=$(echo $LCOV_SUMMARY | sed -n 's/.*lines......: \([0-9.]*%\).*/\1/p' | sed 's/%//')
+      echo "Coverage: $COVERAGE_PERCENTAGE%"
+      if [ $(echo "$COVERAGE_PERCENTAGE < 90" | bc -l) -eq 1 ]; then echo "Error: Coverage is below 90%" && exit 1; fi
   
   artifacts:
     paths:
